Redo greg's proposed change, to figure out what's wrong
This reverts commit f726b214493728894243eca73dbba537d095f6fd.

Now fails thermotest.py:
======================================================================
FAIL: Check the Wilhoit H matches the GA H for propane.
----------------------------------------------------------------------
AssertionError: GA (-97506.0) and Wilhoit (-101546.2) differ by more than 2000.0 J/mol at 400K

======================================================================
FAIL: Check the Wilhoit S matches the GA S for propane.
----------------------------------------------------------------------
AssertionError: GA (294.1) and Wilhoit (282.6) differ by more than 4.0 J/mol/K at 400K

======================================================================
FAIL: Check the Wilhoit Cp matches the GA Cp for propane.
----------------------------------------------------------------------
AssertionError: GA (74.8) and Wilhoit (40.2) differ by more than 4.0 J/mol/K at 300K