Use system site_packages (and numpy/scipy) in travis config.
Currently it spends thousands of lines of log file (and quite some time)
compiling scipy for each build. The Ubuntu apt-get install of python-scipy
should save this, but you need to enable the system site packages (instead
of the isolated virtual environment) to use it. [1,2]

Hopefully this (using the system site packages) also fixes the apparent
failure of rdkit: current build failed with:
echo "Checking you have rdkit..."
Checking you have rdkit...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named rdkit

[1] http://danielnouri.org/notes/2012/11/23/use-apt-get-to-install-python-dependencies-for-travis-ci/
[2] https://github.com/dnouri/nolearn/blob/master/.travis.yml