Refactor julia importing in reactors.py
This should have no material change, just a refactoring
to make it easier to understand the control flow
(which now that I understand, doesn't make much sense to me).

It was introduced in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2364

These timing tests are with 
julia                     1.8.5                h245b042_0    conda-forge
pyjulia                   0.6.1              pyhd8ed1ab_0    conda-forge

  time python-jl rmg.py test/regression/superminimal/input.py
on my 2019 MacBook Pro 2.6Ghz i7 reports
229.82s user 19.77s system 109% cpu 3:48.45 total
although RMG reports Execution time (DD:HH:MM:SS): 00:00:00:40
i.e. it's spent 3 minutes 8 seconds (84% of the total)
compiling julia stuff that's never used.

By running python instead of python-jl
  python rmg.py test/regression/superminimal/input.py
you can get it to run, and it compiles a bunch of julia stuff, 
with more logging, and takes (two runs)
486.58s user 17.46s system 105% cpu 7:58.05 total
499.59s user 17.69s system 105% cpu 8:12.54 total
(again, only 35s reported for RMG Execution time)


And by running 
  python -O rmg.py test/regression/superminimal/input.py
you can get it to run the "if not __debug__:" branch which skips
the Julia runtime making steps, and causes it to print out some
errors like
julia.core.UnsupportedPythonError: It seems your Julia and PyJulia setup are not supported.
and crash.

Later, running 
  time python-jl rmg.py test/regression/superminimal/input.py
I get a lot of warnings like
WARNING: Method definition getGibbs(P, N) where {N<:Number, P<:ReactionMechanismSimulator.AbstractThermo} in module ReactionMechanismSimulator at /opt/miniconda3/envs/rmg_env4/share/julia/packages/ReactionMechanismSimulator/xoDOp/src/Calculators/Thermo.jl:6 overwritten on the same line (check for duplicate calls to `include`).
  ** incremental compilation may be fatally broken for this module **
and then 
1143.19s user 82.00s system 98% cpu 20:47.85 total