Revert "CI docs: separate job step for compiling pyrms"
This reverts commit 4e0fd86bfb732566b526e95f74e5550a484f0718.

Was causing:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/usr/share/miniconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 52, in python
    exec(command, scope)
  File "<string>", line 1, in <module>
  File "/usr/share/miniconda3/envs/rmg_env/lib/python3.7/site-packages/pyrms/rms.py", line 7, in <module>
    from julia import ReactionMechanismSimulator
  File "/usr/share/miniconda3/envs/rmg_env/lib/python3.7/site-packages/julia/core.py", line 260, in load_module
    raise ImportError("{} not found".format(juliapath))
ImportError: ReactionMechanismSimulator not found