Trying to fix yaml (via cantera 2.6) for Lindemann kinetics
The call rmgpy/reaction.py:339: in rmgpy.reaction.Reaction.to_cantera
    rate = ct.TroeRate(
was causing
    TypeError: Argument 'rate' has incorrect type (expected cantera._cantera.Arrhenius, got cantera._cantera.ArrheniusRate)

I think the ct.LindemannRate expects an Arrhenius not an ArrheniusRate.
Thdis was with cantera                   2.6.0            py37hb93dfd8_0    cantera
running on the Ubuntu CI