Trying to fix yaml (via cantera 2.6) for Lindemann kinetics
The call
    rate = ct.LindemannRate(low_rate, high_rate, falloff)
was causing 
    TypeError: Argument 'rate' has incorrect type (expected cantera._cantera.Arrhenius, got cantera._cantera.ArrheniusRate)

I think the ct.LindemannRate expects an Arrhenius not an ArrheniusRate.
Thdis was with cantera                   2.6.0            py37hb93dfd8_0    cantera
running on the Ubuntu CI