Fixes to coverage-dependent kinetics. [requires rebuild of cython]
Danielle reported this:

Traceback (most recent call last):
  File "/Users/daniellelucey/RMG-Py/rmg.py", line 4, in <module>
    __main__.main()
  File "/Users/daniellelucey/RMG-Py/rmgpy/__main__.py", line 102, in main
    rmg.execute(**kwargs)
  File "/Users/daniellelucey/RMG-Py/rmgpy/rmg/main.py", line 1014, in execute
    terminated, resurrected, obj, new_surface_species, new_surface_reactions, t, x = reaction_system.simulate(
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rmgpy/solver/base.pyx", line 572, in rmgpy.solver.base.ReactionSystem.simulate
    cpdef simulate(self, list core_species, list core_reactions, list edge_species,
  File "rmgpy/solver/base.pyx", line 669, in rmgpy.solver.base.ReactionSystem.simulate
    self.initialize_model(core_species, core_reactions,
  File "rmgpy/solver/surface.pyx", line 268, in rmgpy.solver.surface.SurfaceReactor.initialize_model
    ReactionSystem.set_initial_derivative(self)
  File "rmgpy/solver/base.pyx", line 475, in rmgpy.solver.base.ReactionSystem.set_initial_derivative
    self.dydt0 = - self.residual(self.t0, self.y0, np.zeros(self.neq, float), self.senpar)[0]
  File "rmgpy/solver/surface.pyx", line 516, in rmgpy.solver.surface.SurfaceReactor.residual
    surface_site_fraction ** m *\
TypeError: Cannot convert 'complex' with non-zero imaginary component to 'double' (this most likely comes from the '**' operator; use 'cython.cpow(True)' to return 'nan' instead of a complex number).



I'm not sure why it occurred (a negative coverage? a NaN coverage?)
But this might help. Forces all coverages to be >0
And doesn't bother calculating if <1e-6 (previously 1e-15)

I suppose if total_sites is 0, you could still get a NaN, but...?