Try to cope with missing data in States database.
Some nodes (and all parents) have None data.
Without this fix/workaround,
I end up with a group entry.data=None and get an error like this:

Updating 1 modified unimolecular reaction networks...
Traceback (most recent call last):
  File "rmg.py", line 711, in <module>
    execute(args)
  File "rmg.py", line 334, in execute
    reactionModel.enlarge(object, database)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/rmg/model.py", line 942, in enlarge
    self.updateUnimolecularReactionNetworks(database)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/rmg/model.py", line 1403, in updateUnimolecularReactionNetworks
    network.update(self, database)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/rmg/model.py", line 455, in update
    if spec.states is None: spec.generateStatesData(database)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/rmg/model.py", line 139, in generateStatesData
    self.states = database.states.getStatesData(molecule, self.thermo)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/data/states.py", line 545, in getStatesData
    statesModel = self.getStatesDataFromGroups(molecule, thermoModel)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/data/states.py", line 577, in getStatesDataFromGroups
    return self.groups.getStatesData(molecule, thermoModel)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/data/states.py", line 342, in getStatesData
    minDegeneracy, minEntry = min([(entry.data.symmetry, entry) for entry in groupCount if groupCount[entry] > 0])
AttributeError: 'NoneType' object has no attribute 'symmetry'