Replace calls to reaction.isEquivalent with checking products and reactans equal
In commit afbb26b3163e8ec07663f7e83b1df700b05f3ee0 the isEquivalent() method was 
removed. In a few other places it seems to have been replaced with checking
that the reactants and products are equal, so I have done the same here in the
remaining two places where it is called. However, the old function used to 
check in both directions (matching reverse against forward). I am not sure
which is appropriate here.

However, this commit at least removes the bug that crashes like this:

Merging PDepNetwork #37 and PDepNetwork #38
Traceback (most recent call last):
  File "rmg.py", line 711, in <module>
    execute(args)
  File "rmg.py", line 334, in execute
    reactionModel.enlarge(object, database)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/rmg/model.py", line 932, in enlarge
    network0.merge(network)
  File "/Users/rwest/XCodeProjects/RMGpy/RMG-Py/rmgpy/rmg/model.py", line 362, in merge
    if reaction.isEquivalent(rxn):
AttributeError: 'TemplateReaction' object has no attribute 'isEquivalent'